version: '3.7'

services:
  php-fpm:
    image: php:8.2-fpm
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/symfony
    working_dir: /var/www/symfony

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/symfony
      - ./docker/nginx/conf:/etc/nginx/conf.d
    depends_on:
      - php-fpm

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${DB_NAME:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${DB_PASS:-app}
      POSTGRES_USER: ${DB_USER:-app}
    volumes:
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
       - ./docker/db/data:/var/lib/postgresql/data:rw

volumes:
  db_data:
