doctrine:
  orm:
    mappings:
      Product:
        type: xml
        is_bundle: false
        dir: '%kernel.project_dir%/src/Modules/Product/Infrastructure/Entity'
        prefix: 'Whipo\Shop\Modules\Product\Domain\Entity'
        alias: Product